### ISSUE TITLE
Add plots

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/gemviz#132]
[pyQtGraph](https://www.pyqtgraph.org/) or [Matplotlib](https://matplotlib.org/)?

**Comment by prjemian** [comment]
Start with `chart_type="line_1d"`.

These views are more challenging:

view | challenge
--- | ---
`grid_2D` | need to reshape the 1D raw data, noting the snake setting
`scatter_2D` | need to set pixel size and use color map for intensity (signal) scale
`unknown{N}D` | might be an area detector frame set - needs more info to decide

**Comment by prjemian** [comment]
Also, once a view of the default data is solid, then need to decide how to select from the possible data to change the view.

Also, consider how a view can overlay new data.  Possibly a checkbox that says `[ ] new plot` or something clearer.

**Comment by rodolakis** [comment]
I believe `pymca` has a "add to plot" vs "replace" option.

**Comment by prjemian** [comment]
Tutorials:
* [PyQtGraph](https://www.pythonguis.com/tutorials/plotting-pyqtgraph/).
* [MatPlotLib PyPlot](https://matplotlib.org/stable/tutorials/introductory/pyplot.html)

**Comment by prjemian** [comment]
See the _Comparison to other python graphics packages_ section in the [PyQtGraph home page](https://www.pyqtgraph.org/).

Other comparison sites show a two column item-by-item review:

* [libhunt](https://www.libhunt.com/compare-pyqtgraph-vs-matplotlib)
* [sourceforge](https://sourceforge.net/software/compare/Matplotlib-vs-PyQtGraph/)

A [3-package comparison](https://www.pythonguis.com/topics/plotting/).  Also includes _QtCharts_.

**Comment by prjemian** [comment]
Still no solid, independent indicator of which package to pick first.

**Comment by prjemian** [comment]
I'm inclined to try both at the same time, in different tabs of the viz panel.  With that, we can gauge the user experience before settling on one for the production version.

**Comment by prjemian** [comment]
Can we do this with Qt's Model/View design?  We might need several views, one for each type of plot we can render (line_1d, grid_2d, image_2d, image_frames, ...)

We'd need a model that provided data from the rows (runs) selected in the table of runs but we also need a way to change which signals are plotted.  That means we need a new widget (like in PyMca) that shows what signals are available and provides checkboxes and such.

**Comment by prjemian** [comment]
Might help to work through Qt's [*ChartView* tutorial](https://doc.qt.io/qtforpython-5/tutorials/datavisualize/index.html).

**Comment by prjemian** [comment]
That demo is for PySide's QtCharts module, so it gets a bit difficult if you don't have PySide2 installed.
