### ISSUE TITLE
ENH open tiled server dialog

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/gemviz#143]
On Mac, the menu bar of any application is always "detached" from the app windows and shows in the top corner of the monitor. 
<img width="2879" alt="image" src="https://github.com/BCDA-APS/gemviz/assets/39918069/d53f16eb-a294-44aa-8aa0-b13e702f48b4">
On a big screen, that makes it quite inconvenient to go all the way to the top left corner to pull up the open tiled server dialog windows. My first reflex when opening the app was to look into the pull down menu on the right (which is in fact the menu for the catalogs). 

Could we add a button to open the dialog somewhere close to the text "Tiled server URI", or even a pull down menu with the following option:
- index 0: nothing, or if possible some info text such as "select tiled server" (light grey and italic?)
- index 1: last tiled server
- index 2: other
Picking 2 would open the tiled server dialog window (same as File/Open)

**Comment by rodolakis** [comment]
We might also want  to add a label to the catalog Qcombobox, since it got confused at first

**Comment by prjemian** [comment]
We could keep a list of all the successful tiled server connections in the user's settings file.  That list would populate the QComboBox.  While it is expected that most use would only use a single server, this is another _It would be nice if_ feature.
