### ISSUE TITLE
Remember all successful tiled server connections

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#148]
We could keep a list of all the successful tiled server connections in the user's settings file.  That list would populate the QComboBox.  While it is expected that most use would only use a single server, this is another _It would be nice if_ feature.

_Originally posted by @prjemian in https://github.com/BCDA-APS/gemviz/issues/143#issuecomment-1694398202_

**Comment by prjemian** [comment]
Issue #149 would help here.

**Comment by rodolakis** [comment]
Started on that tonight.
