### ISSUE TITLE
Typo in 

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/gemviz#193]
https://github.com/BCDA-APS/gemviz/blob/d0feb9f31b6db214537668d7332dbdd60a186595/gemviz/bluesky_runs_catalog.py#L111C1-L112C36

```py
            if action == "add":
                action == "replace"
```

This second `==`does nothing. Typo?

**Comment by prjemian** [comment]
Right.  Too many `=` signs.

**Comment by prjemian** [comment]
Good first issue to exercise the branch-PR process.  Assigned to Eric.
