### ISSUE TITLE
re-arrange to make more space for visualization

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#200]
- move the Matching Results to a tab next to simple search
- move field selection below the search & runs panel
![image](https://github.com/BCDA-APS/gemviz/assets/2279984/608ca117-b02a-4038-88c3-2612771b6aef)

**Comment by rodolakis** [comment]
Agreed. I had the same thought. Final layout should be closer to the mdaviz one:

![image](https://github.com/BCDA-APS/gemviz/assets/39918069/fe6e1f4e-f050-4ff4-8466-675fc56dc753)

**Comment by prjemian** [comment]
As things stand now:
![image](https://github.com/BCDA-APS/gemviz/assets/2279984/41b8551e-79b2-4f15-9574-19a0ddde3cd5)

First, the `filter_groupbox` needs to be changed into a `filter_panel`.
