### ISSUE TITLE
rename repository to "gemviz23"

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#74]
Seems appropriate to rename this repository to `gemviz23`.

**Comment by olliviergassant** [comment]
Look at the URL below on instruction on changing the repository name

[https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository](url)

**Comment by prjemian** [comment]
Checked both Pypi.org and anaconda.org for packages named `gemviz`: no such package.  Checked GitHub for repos named `gemviz`, found three others, all more than 5 years old and very unrelated.
