### ISSUE TITLE
apply code style programs

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#84]
There are two useful python applications that will refactor the source code to be compliant with best-practice guidelines.  These are:

- [black](https://black.readthedocs.io/)
- [isort](https://pycqa.github.io/isort/)

```bash
cd gemviz23/
black .
isort .
```

**Comment by prjemian** [comment]
Neither of these should change how the code works, just how it looks.

**Comment by rodolakis** [comment]
> ```shell
> cd gemviz23/
> black .
> isort .
> ```

There are VSC extensions to apply both black and isort on save:

https://marketplace.visualstudio.com/items?itemName=ms-python.isort
https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter
