### ISSUE TITLE
Add refresh button for date slider

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/gemviz#93]
Having to press enter in another research field is not very intuitive

**Comment by prjemian** [comment]
Find some buttons here: https://github.com/prjemian/moxy/tree/master/src/moxy/resources

**Comment by prjemian** [comment]
Here's is the old (PyQt4) code from `moxy` that loaded some button images.  Might be easier now doing this in designer.   ...

```py
(base) prjemian@arf:~/.../src/moxy$ git grep bmp
configure.py:LOGO_FILE = 'epicslogo101.bmp'
resources/configure_pv.ui:          <pixmap>epicslogo101.bmp</pixmap>
row.py:        icon = QtGui.QIcon(os.path.join(forms_path, 'delete.bmp'))
row.py:        icon = QtGui.QIcon(os.path.join(forms_path, 'set.bmp'))
row.py:        icon = QtGui.QIcon(os.path.join(forms_path, 'go.bmp'))
```

**Comment by prjemian** [comment]
Instead of `os.path.join(forms_path, 'delete.bmp')`, we might use `resources / "delete.bmp"` where `resources` is a pathlib object to that directory.

**Comment by prjemian** [comment]
Did not yet connect the signal from the new button.
